# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

image: Visual Studio 2019 Preview

branches:
  only:
    - master

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0MrjEwujECMnIaBkI76fNmCpKy5jr9rZx0rAFOM+41frhVfy2r0ldzzoFC4bvGig

install:
- ps: |
    Write-Host "Installing .NET Core SDK..." -ForegroundColor Cyan
    Write-Host "Downloading..."
    $exePath = "$env:TEMP\dotnet-sdk-2.2.100-win-x64.exe"
    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/a7e73d05-4e75-4543-ac41-fc69d2f617e5/3f65a44f90c9df66664b44e86b0e6d29/dotnet-sdk-3.0.100-preview-010184-win-x64.exe', $exePath)
    Write-Host "Installing..."
    cmd /c start /wait "$exePath" /quiet /norestart
    del $exePath
    Write-Host "Installed" -ForegroundColor Green
    
    Write-Host "Installing .NET Core runtime..." -ForegroundColor Cyan
    Write-Host "Downloading..."
    $exePath = "$env:TEMP\dotnet-hosting-2.2.0-win.exe"
    (New-Object Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/1f4548a4-96a4-4905-b222-1115d0f30535/a7eaa7c6565c2273991e0f3ca4c790c9/dotnet-hosting-3.0.0-preview-19075-0444-win.exe', $exePath)
    Write-Host "Installing..."
    cmd /c start /wait "$exePath" /quiet /norestart
    del $exePath
    Write-Host "Installed" -ForegroundColor Green

# Perform the build.
build_script:
  - bash build/appveyor.sh
  - choco install codecov
  - codecov -f coverage/coverage.xml

# The tests are run as part of the build.
test: off
